export const TYPE_SELECT = "TYPE_SELECT";
export const TYPE_UPDATED = "TYPE_UPDATED";
export const OBSERVATION_SELECT = "OBSERVATION_SELECT";
export const OBSERVATION_UPDATED = "OBSERVATION_UPDATED";
export const OBSERVATIONS_REQUEST = "OBSERVATIONS_REQUEST";
export const OBSERVATIONS_REQUEST_SUCCESS = "OBSERVATIONS_REQUEST_SUCCESS";
export const OBSERVATIONS_REQUEST_ERROR = "OBSERVATIONS_REQUEST_ERROR";
export const OBSERVATIONS_UPDATED = "OBSERVATIONS_UPDATED";
