export const STATS_UPDATED = "STATS_UPDATED";
export const STATS_REQUEST = "STATS_REQUEST";
export const STATS_REQUEST_SUCCESS = "STATS_REQUEST_SUCCESS";
export const STATS_REQUEST_ERROR = "STATS_REQUEST_ERROR";
